# Generated by Django 3.2 on 2021-05-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0002_auto_20210505_1254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(max_length=10),
        ),
    ]
