"""
Django settings for tuike_api project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', default='j!i@i+y&bm$23p2v#hss(gv@i=q6x1wusc3gzocodr+*_#_^l@')

ENVIROMENT = os.environ.get('ENVIRONMENT', default="DEV")

if ENVIROMENT == "DEV":
    DEBUG = True
    HOST = "http://localhost:8000"
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
elif ENVIROMENT == "TEST":
    DEBUG = True
    HOST = "https://tuike-api-test.herokuapp.com"
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', "tuike-api-test.herokuapp.com"]
elif ENVIROMENT == "LIVE":
    DEBUG = False
    HOST = "https://tuike-api.herokuapp.com"
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', "tuike-api.herokuapp.com"]

CORS_ORIGIN_WHITELIST = [
    'http://localhost',
    'https://localhost',
    'http://localhost:3000',
    'http://tuike-test.herokuapp.com',
    'http://tuike.herokuapp.com',
    'https://tuike-test.herokuapp.com',
    'https://tuike.herokuapp.com',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'huey.contrib.djhuey',
    'account_service',
	'course_service',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tuike_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tuike_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tuike_test_db',
        'USER': os.environ.get('TUIKE_DB_USER'),
        'PASSWORD': os.environ.get('TUIKE_DB_PASSWORD'),
        'HOST': '47.97.40.237',
        'PORT': '3306'
    }
}

HUEY = {
    'name': 'tuike_api',
    'huey_class': 'huey.RedisHuey',
    'results': True,
    'immediate': False,
    'connection': {
        'host': '47.97.40.237',
        'port': 6380,
        'password': os.environ.get("TUIKE_REDIS_PASSWORD"),
    },
    'consumer': {
        'workers': 4,
        'worker_type': 'thread',
        'scheduler_interval': 1,
        'check_worker_health': True,  # Enable worker health checks.
        'health_check_interval': 1,  # Check worker health every second.
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://47.97.40.237:6380/1",
        "OPTIONS": {
            "PASSWORD": os.environ.get("TUIKE_REDIS_PASSWORD"),
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get("TUIKE_EMAIL_USER")
EMAIL_HOST_PASSWORD = os.environ.get("TUIKE_EMAIL_PASSWORD")
