GET_TEACHER_NAMES_CACHE_PREFIX = "GET_TEACHER_NAMES"
GET_TEACHER_NAMES_CACHE_TIMEOUT = 60 * 30

GET_TEACHERS_BY_COURSE_CACHE_PREFIX = "GET_TEACHERS_BY_COURSE"
GET_TEACHERS_BY_COURSE_CACHE_TIMEOUT = 60 * 30