# Generated by Django 3.2 on 2021-05-12 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_grade',
        ),
    ]
