# Generated by Django 3.2 on 2021-05-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_service', '0002_remove_review_user_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewInteract',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('review_id', models.PositiveBigIntegerField()),
                ('action', models.PositiveSmallIntegerField()),
                ('create_by', models.PositiveBigIntegerField()),
                ('create_time', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'review_interact_tab',
            },
        ),
        migrations.AddIndex(
            model_name='reviewinteract',
            index=models.Index(fields=['review_id', 'action'], name='ri_review_id_action_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewinteract',
            index=models.Index(fields=['create_by'], name='ri_create_by_idx'),
        ),
    ]
