# Generated by Django 3.2 on 2021-05-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_service', '0003_auto_20210518_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewinteract',
            name='action',
            field=models.SmallIntegerField(),
        ),
    ]
