# Generated by Django 3.2 on 2021-05-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('review_count', models.PositiveIntegerField()),
                ('recommend_score', models.FloatField(default=0)),
                ('exam_score', models.FloatField(default=0)),
                ('work_score', models.FloatField(default=0)),
                ('content_score', models.FloatField(default=0)),
                ('create_time', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'teacher_tab',
            },
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['name'], name='teacher_name_idx'),
        ),
    ]
