# Generated by Django 3.2 on 2021-05-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
