from common.consts import *

TEST_EMAIL = 'test_example@pku.edu.cn'
TEST_VERIFICATION_CODE = '123456'
TEST_UID = 3
TEST_COURSE_ID = 1824
TEST_TEACHER_ID = 3241
TEST_REVIEW_ID = 2
TEST_SEMESTER = "20-21-2"
TEST_SCHOOL_ID = 1